### ISSUE TITLE
"no 'dim names' attribute for array" Issue with CSS on ATAC assay

### ISSUE THREAD

**Issue by yojetsharma** [quadbiolab/simspec#12]
I am following the scmultiome tutorial (https://github.com/quadbio/scMultiome_analysis_vignette/blob/main/Tutorial.md#step-45-data-integration-of-the-atac-assay) and I have a list of 4-multiome files which are `merged` and everything runs fine except when I reach ATAC assay section:

```
>> seurat
An object of class Seurat 
384283 features across 37917 samples within 2 assays 
Active assay: ATAC (347682 features, 346480 variable features)
 1 other assay present: RNA
 6 dimensional reductions calculated: lsi, umap_atac, pca, umap_rna, css_rna, umap_css_rna
> library(simspec)
> seurat <- cluster_sim_spectrum(seurat,
+                                label_tag = "orig.ident",
+                                use_dr = "lsi",
+                                dims_use = 2:30,
+                                cluster_resolution = 0.6,
+                                reduction.name = "css_atac",
+                                reduction.key = "CSSATAC_")
Error in object[[object@active.assay]]@scale.data[var_genes, ] : 
  no 'dimnames' attribute for array
```

**Comment by zhisonghe** [comment]
Hi, this is due to the recent update which makes unnecessary subset of the scale.data matrix. An update has just been pushed to fix the bug.

**Comment by yojetsharma** [comment]
> Hi, this is due to the recent update which makes unnecessary subset of the scale.data matrix. An update has just been pushed to fix the bug.

Oh great, thanks! Has it been updated now or should I wait for few more days and then re-install simspec and try it again?

**Comment by zhisonghe** [comment]
You can now reinstall simspec and it should work.

**Comment by yojetsharma** [comment]
> You can now reinstall simspec and it should work.

Yes, it worked. Thank you!
