### ISSUE TITLE
Error in cor(as.matrix(data), profiles, method = corr_method) :    'y' must be numeric

### ISSUE THREAD

**Issue by hummuscience** [quadbiolab/simspec#2]
Ran into this error using seurat object

```
sobj <- merge(sobj.list[[1]], sobj.list[2:6], merge.data = TRUE)
sobj.features <- SelectIntegrationFeatures(object.list = sobj.list, nfeatures = 3000)
sobj <- RunPCA(sobj, features = sobj.features, npcs = 100, verbose = TRUE)
sobj <- cluster_sim_spectrum(sobj, label_tag = "dataset")
```
The individual clustering works for each dataset but then the error appears.

```
>> Done clustering of sample Zim2.
Finished clustering.
Obtained average profiles of clusters.
Start to calculate standardized similarities to clusters...
Error in cor(as.matrix(data), profiles, method = corr_method) : 
  'y' must be numeric
> 
```

**Comment by zhisonghe** [comment]
Hi,

Can you check whether you have variable features already defined in your sobj object, by checking length(VariableFeatures(sobj))? By default cluster_sim_spectrum calls this list to calculate transcriptome similarities so it cannot be empty.

You can assign your sobj.features as the variable features of the object before running cluster_sim_spec, via
VariableFeatures(sobj) <- sobj.features

Alternatively, you can set the var_genes parameter in the cluster_sim_spectrum function, e.g.
sobj <- cluster_sim_spectrum(sobj, var_genes = sobj.features, label_tag = “dataset")

Hope this helps.


On 5 May 2020, at 22:59, Muad Abd El Hay <notifications@github.com<mailto:notifications@github.com>> wrote:



Ran into this error using seurat object

sobj <- merge(sobj.list[[1]], sobj.list[2:6], merge.data = TRUE)
sobj.features <- SelectIntegrationFeatures(object.list = sobj.list, nfeatures = 3000)
sobj <- RunPCA(sobj, features = sobj.features, npcs = 100, verbose = TRUE)
sobj <- cluster_sim_spectrum(sobj, label_tag = "dataset")


The individual clustering works for each dataset but then the error appears.

>> Done clustering of sample Zim2.
Finished clustering.
Obtained average profiles of clusters.
Start to calculate standardized similarities to clusters...
Error in cor(as.matrix(data), profiles, method = corr_method) :
  'y' must be numeric

**Comment by hummuscience** [comment]
Indeed, this solved the issue!
Maybe an informative warning could help avoid this?
Or a way to calculate variable genes? For seurat one can use the method I used above
