### ISSUE TITLE
NAs produced after running cluster_sim_spectrum on seurat object

### ISSUE THREAD

**Issue by kaizen89** [quadbiolab/simspec#3]
I was quite happy with `simspec`, It did really improve my clustering. However, recently I had more samples to integrate and faced a problem  which is shown bellow.
```
merge <- cluster_sim_spectrum(merge, label_tag = "patient_ID", dims_use = 1:20, redo_pca = F, reduction.name="css",k=20, corr_method = "pearson",spectrum_type="corr_kernel", cluster_resolution = 1)
anyNA(Embeddings(bladder_merge, "pca"))
>FALSE
anyNA(Embeddings(bladder_merge, "css"))
>TRUE
```
Because of the NAs I can not continue with the rest of the clustering. Any idea where is this coming from?

**Comment by zhisonghe** [comment]
Can you provide more information, especially if there is any warning or error message when CSS was run?

To my experience this is possibly because of an empty variable feature list in the provided Seurat object, so all the correlations became NA, but I'm not sure at the moment.

**Comment by kaizen89** [comment]
![image](https://user-images.githubusercontent.com/30392707/86369157-5703f600-bc7e-11ea-9cc9-dc4ae3a9e63a.png)

**Comment by zhisonghe** [comment]
This is very uncommon.

One possibility that comes to my mind is that for some cells in your data set none of the highly variable genes are detected, therefore with all zero expression levels resulting in zero standard deviation which made the correlation NA. Could you check whether NAs only exist in a small set of cells in the CSS matrix, or the whole matrix is NA? If there were only a subset of cells with NAs, you may then check whether it is the case that those cells didn't express the highly variable genes.

**Comment by kaizen89** [comment]
There is indeed one cell which does not express any of the variable genes.
```
Matrix::colSums(merge@assays$RNA@counts[vargenes,"HSB42S_AGTGTTGTCTTCCAGC-1", drop=F])
HSB42S_AGTGTTGTCTTCCAGC-1 
                       0 
```
Thanks a lot for your help
