### ISSUE TITLE
Adjusted expression matrix after CSS integration ?

### ISSUE THREAD

**Issue by JosephLeger** [quadbiolab/simspec#7]
Hello,
I'm currently working on developmental datasets, and this tool you developed seems to perform a much much better integration than any others. However, I'm interested in gene expression variation along developmental trajectories, and I was wondering if there was a way to get integrated data values ?
I would like to have a modified expression matrix that fit with integrated representation using CSS integration, similarly to Seurat's integration which gives a new object with expression adjustment after integration. 

Maybe it's not possible, but I'm not sure that using non integrated data values for downstream expression analysis based on CSS integrated representation is relevant in my case...

Thanks for your work,
Best,
Joseph

**Comment by zhisonghe** [comment]
Hi, Joseph,

Unfortunately there is currently no support to "correct" the original expression matrix based on the CSS integrated representation. In principle we can implement a similar correction scheme as Seurat does, but as CSS representation doesn't require that, we didn't involve that functionality. In fact, even with the Seurat integration, it is suggested to "[use the RNA assay when exploring the genes that change either across clusters, trajectories, or conditions](https://github.com/satijalab/seurat/issues/1717)", we therefore don't feel the necessity to implement it right now.

All the best,
Zhisong

**Comment by JosephLeger** [comment]
Hello,

Thank you very much for your answer which is very helpful ! I hadn't noticed that point for Seurat either.

Thanks again for your work,
Best,
Joseph
